name: .NET Core Desktop

permissions:
  contents: write
  issues: write

on:
  push:
    tags:
      - '*'  # This will trigger the workflow on tag creation.
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: VirtualMicApp.sln
      Project_Path: VirtualMicApp/VirtualMicApp.csproj
      Output_Directory: VirtualMicApp/bin/${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }}

    - name: Build the project
      run: dotnet build ${{ env.Project_Path }} --configuration ${{ matrix.configuration }}

    - name: Zip everything built
      run: |
        cd $env:Output_Directory
        Compress-Archive -Path * -DestinationPath ../VirtualMicApp-${{ matrix.configuration }}.zip
      shell: pwsh

    - name: Upload Zip as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build Output
        path: VirtualMicApp-${{ matrix.configuration }}.zip

  recreate_release:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Delete Existing Release
        id: delete_release
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag = "v1";
      
            // List all releases and find the release by tag
            const releases = await github.rest.repos.listReleases({
              owner: owner,
              repo: repo,
            });
      
            const release = releases.data.find(release => release.tag_name === tag);
      
            // Check if the release exists and delete it
            if (release) {
              await github.rest.repos.deleteRelease({
                owner: owner,
                repo: repo,
                release_id: release.id,
              });
              console.log(`Deleted release with ID ${release.id}`);
            } else {
              console.log("No existing release to delete");
            }
      
            // Delete the tag
            try {
              await github.rest.git.deleteRef({
                owner: owner,
                repo: repo,
                ref: `tags/${tag}`,
              });
              console.log(`Deleted tag ${tag}`);
            } catch (error) {
              console.error(`Error deleting tag: ${error.message}`);
            }

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build Output

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v1
          tag_name: v1
          body: |
            **This release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            yeahhh :D
          files: |
            VirtualMicApp-${{ matrix.configuration }}.zip
